fn_args_layout = "Vertical"
reorder_imports = true
group_imports = "StdExternalCrate"
imports_indent = "Block"
imports_layout = "Vertical"
fn_single_line = true
match_block_trailing_comma = true
struct_field_align_threshold = 0
struct_lit_single_line = false
use_field_init_shorthand = true
wrap_comments = true